# Generated by Django 4.2.7 on 2023-12-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userbankaccount_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='isBankCraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Is_Bank_Craft', models.BooleanField(default=False)),
            ],
        ),
    ]
