# Generated by Django 4.2.7 on 2023-12-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[(1, 'deposit'), (2, 'withdrawal'), (3, 'loan'), (4, 'loan Paid')], max_length=100, null=True),
        ),
    ]
